sudo: required
env:
  global:
  # DOCKER_PASSWORD
  - secure: "QuM2DBRguEDUalQmfgHriv/C6ftk0GyAHypMrMA4Vqki8O0W5HKeqNzRNAElrUzYzElDYq/rrTXINaRTiCoMgbSOe1i9vnQYFCNcqN0RZRsiNvrzLhB+NC2IQ/kU73EAxT4cej2oHF6HJAUIPEHogZUCzUBZNAIo/z7vGfNnuHflfzlECehkxruj/WIpJBLRw1b1uPS3Oa6oFa7L3fs7HR70W17/Ple1YtV985MbLovzs2UYEtBgDbs44zF3rjrFvBcOyft64fk8uIs4JdcuAx7lY8LfL2WHoVKreRyBU9fANagr1nobArRAIzSuCGfDoCyFn36iyuu7LjCAUedM+YxySJKoMYLdbsYcHmijHEEGCQ5ytwxmuEzGRq6XZHvUFD2FfbFPmIRmWnt+7N/l+3tOgZo9Fg5OnPpz16ajavckso4TRq7tyHBmti1HyDYVTafeLrMlrB/MwDQHV4CyUBO1G1nndHAxR+8Z4LHupjEmPxWS2nPT6ND+KhWp+3E3b0Q1+5H1jUM3x3rKyDaw7RNWciGnYfaR01DQOVGg5HvQ+GGMvLPUHEeOy5hC1nxp6K67XeOBSMzqGqGlNSXy4Ykq+4T8uBjXP2HMqkFc8/5C4mgWf5ZQgUyJtF27w/sTx5VV7fmVfT5A5WlUtdQP5DeD7+lY0d/t2pU7TwVMi8s="
  - DOCKER_USERNAME: untangleengineering
  - GOPATH="${HOME}/go"
  - DIR="${GOPATH}/src/github.com/untangle"
  matrix:
  - TARGET=glibc
  - TARGET=musl
services:
- docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- mkdir -p "$DIR"
- mv "$TRAVIS_BUILD_DIR" "${DIR}/golang-shared"
- cd "${DIR}/golang-shared"
script:
- docker-compose -f build/docker-compose.build.yml up --build ${TARGET}-local || travis_terminate 1
notifications:
  email: false
  slack:
    rooms:
      secure: "Ct7k1mJNZ9qfAKoA/3RPHohYaRbvr4GZCA0In08ZKpMA2oeQauyO5xB7homM4LtgSoOJul1+kOXU8Nfsl0RyunKt7njBx51tWKTPNg49js4Wr1TGhriBhqnqES9Bghwp5kroSYD1m7NsjoAThy+SQYHOefAfkCy4hQin1OH0TflVRwMT5m3s+pQNzNjqXiEmpsOQ85Vvy8rHdEFiR/rREIUiBtWh07F/X6/ObepFRuleUCdx7QOPQZ5qlBlpqFr3iRDd9hSvv9lftM0vRO5xyuSDmlh6IVdLd2sYtNCQ90DI4N5axK7oCStm4XBc97IhrcIfiigE2RWlp4Ufll1SX1hoyNzhzNsTEir7OnnE+r0uyDGT1E21Gy20Y6rGSRuTW4s8t7vyKpEQEHd7JDiaXPmrSoGC4evzLi1nq9ePZYvLBjnM+0uTkbFZs5xqBHSdUQgdZvOppeGkB/F0vz6nZTS3pR2/uym6A9UnTKfh42xi4tgDJDIz0e9mqjCu0tzCF/oFP83vppEB8P3y00VzunalOTHn6pTPMNaqUpQV3bKiCT0VXk/ScsS3F8JOvDwi2n6/3/QbCYnzsxnvWXv6NijOL+uZM+/gJMUymc9MmiKVjQsHtSehyhL2mcPxKQdOk0l567RDUuSssCIMAQgW6Pc/KIaqutV1WNue54N7nT4="
    on_success: change
    on_failure: always
