sudo: required
dist: focal

env:
  global:
    # DOCKER_PASSWORD
    - secure: QuM2DBRguEDUalQmfgHriv/C6ftk0GyAHypMrMA4Vqki8O0W5HKeqNzRNAElrUzYzElDYq/rrTXINaRTiCoMgbSOe1i9vnQYFCNcqN0RZRsiNvrzLhB+NC2IQ/kU73EAxT4cej2oHF6HJAUIPEHogZUCzUBZNAIo/z7vGfNnuHflfzlECehkxruj/WIpJBLRw1b1uPS3Oa6oFa7L3fs7HR70W17/Ple1YtV985MbLovzs2UYEtBgDbs44zF3rjrFvBcOyft64fk8uIs4JdcuAx7lY8LfL2WHoVKreRyBU9fANagr1nobArRAIzSuCGfDoCyFn36iyuu7LjCAUedM+YxySJKoMYLdbsYcHmijHEEGCQ5ytwxmuEzGRq6XZHvUFD2FfbFPmIRmWnt+7N/l+3tOgZo9Fg5OnPpz16ajavckso4TRq7tyHBmti1HyDYVTafeLrMlrB/MwDQHV4CyUBO1G1nndHAxR+8Z4LHupjEmPxWS2nPT6ND+KhWp+3E3b0Q1+5H1jUM3x3rKyDaw7RNWciGnYfaR01DQOVGg5HvQ+GGMvLPUHEeOy5hC1nxp6K67XeOBSMzqGqGlNSXy4Ykq+4T8uBjXP2HMqkFc8/5C4mgWf5ZQgUyJtF27w/sTx5VV7fmVfT5A5WlUtdQP5DeD7+lY0d/t2pU7TwVMi8s=
    - DOCKER_USERNAME: untangleengineering
    - GOPATH="${HOME}/go"
    - DIR="${GOPATH}/src/github.com/untangle"

    # UNTANGLE_BOT_OATH_TOKEN
    - secure: R9Q9Nyx1Wimy2fbvY3tOpVNWTl8f2pWTunE1VQWzQStJuZWASZr3FnkFFQ4DfgnxGeEqDYZiybxFNkVYJ/ZRcjoc+HRJHglzOjlsyBPt/bKGJHa1SE9czT6Lo0xvudIyICtapOjIwvqIGSaaW73nzBGBh6Hyy+lK2TXbep7oXGR3Hkoxg49/XzHN1BwHlUxW4OmXXSREmRTyKXNxh9qTcUWPkw2OPk4KKRrXmWo/k2UQlETUynJyVmbAoPaGWKVOCcuvYnu51nv5YoqGRAJ8a2J1ENg8mDgxfi2ExHh2rdrooglFQCo+/nc6PehYleb03EuPFg8WAFt72FvpcyX/VyPWZomb5Dx1Ye1PEmD+nsvoDwde9KyKaqAbLY8pRLWj1BOfDbOyN+FdD+1gMSEVnHiD0K8zqJEEtmVxCiOzszazSOW+lW04U/fTlVdfIxY6H28s/GQmBbYKvVsRUsb2vlRvb5WB97+LTL23ZkYqI4Wmplwd+N3oUsoUAU1WNlQu5HahcPDkEzzjlW4leF+oAWRg1LcYQx/9/cnZpz2i/6RpKLkJE2htUdHwo7Xo5kkeFRka1gsXdjwuxQQmYgr/ueELXfYjnEPUKy3LwfOb1lyzQjD1b50++k0ZhPr0/hE8Ap2vhtvO8lshkFeF+oKD5XgVTWJTPcHcxE9vlmCCjQU=
  jobs:
    - TARGET=glibc
    - TARGET=musl
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - mkdir -p "$DIR"
  - cp -R "$TRAVIS_BUILD_DIR" "${DIR}/golang-shared"

script:
  - pushd "${DIR}/golang-shared"
  - docker-compose -f build/docker-compose.build.yml up --abort-on-container-exit --build ${TARGET}-local || travis_terminate 1
  - popd

jobs:
  include:
    - stage: deploy
      env: TARGET=musl
      before_deploy:
        - yes | gem update --system --force
        - gem install bundler
        - gem install faraday-net_http -v '3.3.0' # Fix faraday version
        - gem install uri
        - gem install logger
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@travis-ci.org"
        - export TRAVIS_TAG=v1.64.13
        - if [ -n "$TRAVIS_TAG" ] && [ ! $(git tag -l "$TRAVIS_TAG") ]; then git tag $TRAVIS_TAG; else echo "Uh-oh, tag $TRAVIS_TAG already exists!";  VERSION=$(echo $TRAVIS_TAG | sed 's/^v//');  NEW_VERSION=$(echo $VERSION | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}') ; TRAVIS_TAG="v$NEW_VERSION" ; echo "New tag $TRAVIS_TAG" ; git tag $TRAVIS_TAG ;fi
        - RELEASE_NOTES=${TRAVIS_COMMIT_MESSAGE//$'\n'/ }

      # This needs to be here, otherwise travis will try to take some
      # default action. But we only need to tag.
      script: /bin/true
      deploy:
        - provider: releases
          skip_cleanup: true
          token: "$UNTANGLE_BOT_OATH_TOKEN"
          name: "$TRAVIS_TAG"
          release_notes: "$RELEASE_NOTES"
          on:
            branch: master
        - provider: releases
          skip_cleanup: true
          token: "$UNTANGLE_BOT_OATH_TOKEN"
          name: "$TRAVIS_TAG"
          release_notes: "$RELEASE_NOTES"
          on:
            branch: eft
        - provider: releases
          skip_cleanup: true
          token: "$UNTANGLE_BOT_OATH_TOKEN"
          name: "$TRAVIS_TAG"
          release_notes: "$RELEASE_NOTES"
          on:
            branch: mfw-release-6.1   
