reponame: code.arista.io/efw/protobufs
description: |
  Untangle shared protobufs and golang libraries
users:
  maintainers:
    - abriles@arista.com
    - al.parker@arista.com
    - acooke@arista.com
    - avinash.dige@arista.com
    - crassmussen@arista.com
    - cblaise@arista.com
    - dhadarau@arista.com
    - donal@arista.com
    - iramasamy@arista.com
    - jphillips@arista.com
    - jsommerville@arista.com
    - k.skrzypczyn@arista.com
    - ksridhar@arista.com
    - sdelafond@arista.com
    - smitropoulos@arista.com
    - sumedha.game@arista.com
    - utkarsh.pratapsingh@arista.com
    - vishal.mane-ext@arista.com
  watchers:
    - bruce@arista.com
    - cmercer@arista.com
    - drush@arista.com
    - jcoffin@arista.com
    - prashant.karunakaran@arista.com
    - sheck@arista.com
    - tkovalev@arista.com
x-bar:
  version: production
  target-branch-re: "^(.+-trunk|main|engprod-parent|master|.+-(?:maint|rel|bringup))$"

ObsoleteNames:
  - github.com/untangle/golang-shared

epoch: 1

x-github-bridge:
  reviews:
    - image: test/efw-protobufs
      events:
        - type: merge_group
          branch-re: ^master$
        - type: pull_request
          branch-re: ^master$
        - type: push
          branch-re: ^master$

    - image: tests/renovate-json5
      events:
        - type: pull_request
          branch-re: ^main$
        - type: merge_group
          branch-re: ^main$
        - type: push
          branch-re: ^main$
