// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.14.0
// source: Captiveportal.proto

package CaptivePortal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CaptivePortalGrpcService_GetCaptivePortalUser_FullMethodName = "/captiveportal.CaptivePortalGrpcService/getCaptivePortalUser"
	CaptivePortalGrpcService_SetCaptivePortalUser_FullMethodName = "/captiveportal.CaptivePortalGrpcService/setCaptivePortalUser"
)

// CaptivePortalGrpcServiceClient is the client API for CaptivePortalGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CaptivePortalGrpcServiceClient interface {
	GetCaptivePortalUser(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error)
	SetCaptivePortalUser(ctx context.Context, in *UserSetRequest, opts ...grpc.CallOption) (*UserSetResponse, error)
}

type captivePortalGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptivePortalGrpcServiceClient(cc grpc.ClientConnInterface) CaptivePortalGrpcServiceClient {
	return &captivePortalGrpcServiceClient{cc}
}

func (c *captivePortalGrpcServiceClient) GetCaptivePortalUser(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetResponse)
	err := c.cc.Invoke(ctx, CaptivePortalGrpcService_GetCaptivePortalUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captivePortalGrpcServiceClient) SetCaptivePortalUser(ctx context.Context, in *UserSetRequest, opts ...grpc.CallOption) (*UserSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSetResponse)
	err := c.cc.Invoke(ctx, CaptivePortalGrpcService_SetCaptivePortalUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptivePortalGrpcServiceServer is the server API for CaptivePortalGrpcService service.
// All implementations should embed UnimplementedCaptivePortalGrpcServiceServer
// for forward compatibility
type CaptivePortalGrpcServiceServer interface {
	GetCaptivePortalUser(context.Context, *UserGetRequest) (*UserGetResponse, error)
	SetCaptivePortalUser(context.Context, *UserSetRequest) (*UserSetResponse, error)
}

// UnimplementedCaptivePortalGrpcServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCaptivePortalGrpcServiceServer struct {
}

func (UnimplementedCaptivePortalGrpcServiceServer) GetCaptivePortalUser(context.Context, *UserGetRequest) (*UserGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCaptivePortalUser not implemented")
}
func (UnimplementedCaptivePortalGrpcServiceServer) SetCaptivePortalUser(context.Context, *UserSetRequest) (*UserSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCaptivePortalUser not implemented")
}

// UnsafeCaptivePortalGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptivePortalGrpcServiceServer will
// result in compilation errors.
type UnsafeCaptivePortalGrpcServiceServer interface {
	mustEmbedUnimplementedCaptivePortalGrpcServiceServer()
}

func RegisterCaptivePortalGrpcServiceServer(s grpc.ServiceRegistrar, srv CaptivePortalGrpcServiceServer) {
	s.RegisterService(&CaptivePortalGrpcService_ServiceDesc, srv)
}

func _CaptivePortalGrpcService_GetCaptivePortalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptivePortalGrpcServiceServer).GetCaptivePortalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptivePortalGrpcService_GetCaptivePortalUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptivePortalGrpcServiceServer).GetCaptivePortalUser(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptivePortalGrpcService_SetCaptivePortalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptivePortalGrpcServiceServer).SetCaptivePortalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptivePortalGrpcService_SetCaptivePortalUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptivePortalGrpcServiceServer).SetCaptivePortalUser(ctx, req.(*UserSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CaptivePortalGrpcService_ServiceDesc is the grpc.ServiceDesc for CaptivePortalGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptivePortalGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "captiveportal.CaptivePortalGrpcService",
	HandlerType: (*CaptivePortalGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getCaptivePortalUser",
			Handler:    _CaptivePortalGrpcService_GetCaptivePortalUser_Handler,
		},
		{
			MethodName: "setCaptivePortalUser",
			Handler:    _CaptivePortalGrpcService_SetCaptivePortalUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Captiveportal.proto",
}
