// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: PacketdReply.proto

package PacketdReply

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conntracks []*PacketdReply_ConntrackTableEntry `protobuf:"bytes,1,rep,name=Conntracks,proto3" json:"Conntracks,omitempty"`
}

func (x *PacketdReply) Reset() {
	*x = PacketdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PacketdReply_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketdReply) ProtoMessage() {}

func (x *PacketdReply) ProtoReflect() protoreflect.Message {
	mi := &file_PacketdReply_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketdReply.ProtoReflect.Descriptor instead.
func (*PacketdReply) Descriptor() ([]byte, []int) {
	return file_PacketdReply_proto_rawDescGZIP(), []int{0}
}

func (x *PacketdReply) GetConntracks() []*PacketdReply_ConntrackTableEntry {
	if x != nil {
		return x.Conntracks
	}
	return nil
}

type PacketdReply_ConntrackTableEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values map[int32]*_struct.Struct `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PacketdReply_ConntrackTableEntry) Reset() {
	*x = PacketdReply_ConntrackTableEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PacketdReply_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketdReply_ConntrackTableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketdReply_ConntrackTableEntry) ProtoMessage() {}

func (x *PacketdReply_ConntrackTableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_PacketdReply_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketdReply_ConntrackTableEntry.ProtoReflect.Descriptor instead.
func (*PacketdReply_ConntrackTableEntry) Descriptor() ([]byte, []int) {
	return file_PacketdReply_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PacketdReply_ConntrackTableEntry) GetValues() map[int32]*_struct.Struct {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_PacketdReply_proto protoreflect.FileDescriptor

var file_PacketdReply_proto_rawDesc = []byte{
	0x0a, 0x12, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x02, 0x0a, 0x0c,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x43, 0x6f, 0x6e,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x1a, 0xb8, 0x01, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x4d, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x35, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x52,
	0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x75, 0x6e, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2f,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PacketdReply_proto_rawDescOnce sync.Once
	file_PacketdReply_proto_rawDescData = file_PacketdReply_proto_rawDesc
)

func file_PacketdReply_proto_rawDescGZIP() []byte {
	file_PacketdReply_proto_rawDescOnce.Do(func() {
		file_PacketdReply_proto_rawDescData = protoimpl.X.CompressGZIP(file_PacketdReply_proto_rawDescData)
	})
	return file_PacketdReply_proto_rawDescData
}

var file_PacketdReply_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PacketdReply_proto_goTypes = []interface{}{
	(*PacketdReply)(nil),                     // 0: reports.PacketdReply
	(*PacketdReply_ConntrackTableEntry)(nil), // 1: reports.PacketdReply.ConntrackTableEntry
	nil,                                      // 2: reports.PacketdReply.ConntrackTableEntry.ValuesEntry
	(*_struct.Struct)(nil),                   // 3: google.protobuf.Struct
}
var file_PacketdReply_proto_depIdxs = []int32{
	1, // 0: reports.PacketdReply.Conntracks:type_name -> reports.PacketdReply.ConntrackTableEntry
	2, // 1: reports.PacketdReply.ConntrackTableEntry.Values:type_name -> reports.PacketdReply.ConntrackTableEntry.ValuesEntry
	3, // 2: reports.PacketdReply.ConntrackTableEntry.ValuesEntry.value:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_PacketdReply_proto_init() }
func file_PacketdReply_proto_init() {
	if File_PacketdReply_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PacketdReply_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PacketdReply_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketdReply_ConntrackTableEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PacketdReply_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PacketdReply_proto_goTypes,
		DependencyIndexes: file_PacketdReply_proto_depIdxs,
		MessageInfos:      file_PacketdReply_proto_msgTypes,
	}.Build()
	File_PacketdReply_proto = out.File
	file_PacketdReply_proto_rawDesc = nil
	file_PacketdReply_proto_goTypes = nil
	file_PacketdReply_proto_depIdxs = nil
}
