// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: captiveportal.proto

package CaptivePortalEvent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client string `protobuf:"bytes,1,opt,name=Client,proto3" json:"Client,omitempty"`
}

func (x *UserEventRequest) Reset() {
	*x = UserEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_captiveportal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEventRequest) ProtoMessage() {}

func (x *UserEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_captiveportal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEventRequest.ProtoReflect.Descriptor instead.
func (*UserEventRequest) Descriptor() ([]byte, []int) {
	return file_captiveportal_proto_rawDescGZIP(), []int{0}
}

func (x *UserEventRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type UserEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client   string `protobuf:"bytes,1,opt,name=Client,proto3" json:"Client,omitempty"`
	PolicyId string `protobuf:"bytes,2,opt,name=PolicyId,proto3" json:"PolicyId,omitempty"`
	ConfigId string `protobuf:"bytes,3,opt,name=ConfigId,proto3" json:"ConfigId,omitempty"`
}

func (x *UserEventResponse) Reset() {
	*x = UserEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_captiveportal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEventResponse) ProtoMessage() {}

func (x *UserEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captiveportal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEventResponse.ProtoReflect.Descriptor instead.
func (*UserEventResponse) Descriptor() ([]byte, []int) {
	return file_captiveportal_proto_rawDescGZIP(), []int{1}
}

func (x *UserEventResponse) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *UserEventResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UserEventResponse) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

type UserAcceptTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client      string `protobuf:"bytes,1,opt,name=Client,proto3" json:"Client,omitempty"`
	Acceptdtime string `protobuf:"bytes,2,opt,name=Acceptdtime,proto3" json:"Acceptdtime,omitempty"`
}

func (x *UserAcceptTime) Reset() {
	*x = UserAcceptTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_captiveportal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAcceptTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAcceptTime) ProtoMessage() {}

func (x *UserAcceptTime) ProtoReflect() protoreflect.Message {
	mi := &file_captiveportal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAcceptTime.ProtoReflect.Descriptor instead.
func (*UserAcceptTime) Descriptor() ([]byte, []int) {
	return file_captiveportal_proto_rawDescGZIP(), []int{2}
}

func (x *UserAcceptTime) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *UserAcceptTime) GetAcceptdtime() string {
	if x != nil {
		return x.Acceptdtime
	}
	return ""
}

type UserAcceptTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Done bool `protobuf:"varint,1,opt,name=Done,proto3" json:"Done,omitempty"`
}

func (x *UserAcceptTimeResponse) Reset() {
	*x = UserAcceptTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_captiveportal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAcceptTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAcceptTimeResponse) ProtoMessage() {}

func (x *UserAcceptTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_captiveportal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAcceptTimeResponse.ProtoReflect.Descriptor instead.
func (*UserAcceptTimeResponse) Descriptor() ([]byte, []int) {
	return file_captiveportal_proto_rawDescGZIP(), []int{3}
}

func (x *UserAcceptTimeResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_captiveportal_proto protoreflect.FileDescriptor

var file_captiveportal_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x55, 0x73, 0x65,
	0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x63, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x64, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x64, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x44, 0x6f, 0x6e, 0x65, 0x32, 0xe3, 0x01, 0x0a, 0x10, 0x43, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x65, 0x0a, 0x14, 0x67, 0x65, 0x74,
	0x43, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x24, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x6c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x69, 0x76,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x68, 0x0a, 0x14, 0x73, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f,
	0x72, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x69,
	0x76, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x2a, 0x2e, 0x63,
	0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6e, 0x74, 0x61, 0x6e, 0x67, 0x6c,
	0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2f, 0x43, 0x61, 0x70, 0x74, 0x69, 0x76, 0x65, 0x50,
	0x6f, 0x72, 0x74, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_captiveportal_proto_rawDescOnce sync.Once
	file_captiveportal_proto_rawDescData = file_captiveportal_proto_rawDesc
)

func file_captiveportal_proto_rawDescGZIP() []byte {
	file_captiveportal_proto_rawDescOnce.Do(func() {
		file_captiveportal_proto_rawDescData = protoimpl.X.CompressGZIP(file_captiveportal_proto_rawDescData)
	})
	return file_captiveportal_proto_rawDescData
}

var file_captiveportal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_captiveportal_proto_goTypes = []interface{}{
	(*UserEventRequest)(nil),       // 0: captiveportalevent.UserEventRequest
	(*UserEventResponse)(nil),      // 1: captiveportalevent.UserEventResponse
	(*UserAcceptTime)(nil),         // 2: captiveportalevent.UserAcceptTime
	(*UserAcceptTimeResponse)(nil), // 3: captiveportalevent.UserAcceptTimeResponse
}
var file_captiveportal_proto_depIdxs = []int32{
	0, // 0: captiveportalevent.CaptiveUserEvent.getCaptivePortalUser:input_type -> captiveportalevent.UserEventRequest
	2, // 1: captiveportalevent.CaptiveUserEvent.setCaptivePortalUser:input_type -> captiveportalevent.UserAcceptTime
	1, // 2: captiveportalevent.CaptiveUserEvent.getCaptivePortalUser:output_type -> captiveportalevent.UserEventResponse
	3, // 3: captiveportalevent.CaptiveUserEvent.setCaptivePortalUser:output_type -> captiveportalevent.UserAcceptTimeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_captiveportal_proto_init() }
func file_captiveportal_proto_init() {
	if File_captiveportal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_captiveportal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_captiveportal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_captiveportal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAcceptTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_captiveportal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAcceptTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_captiveportal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_captiveportal_proto_goTypes,
		DependencyIndexes: file_captiveportal_proto_depIdxs,
		MessageInfos:      file_captiveportal_proto_msgTypes,
	}.Build()
	File_captiveportal_proto = out.File
	file_captiveportal_proto_rawDesc = nil
	file_captiveportal_proto_goTypes = nil
	file_captiveportal_proto_depIdxs = nil
}
