// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: ActiveSessions.proto

package ActiveSessions

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActiveSessions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionsList []*_struct.Struct `protobuf:"bytes,1,rep,name=sessionsList,proto3" json:"sessionsList,omitempty"`
}

func (x *ActiveSessions) Reset() {
	*x = ActiveSessions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ActiveSessions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSessions) ProtoMessage() {}

func (x *ActiveSessions) ProtoReflect() protoreflect.Message {
	mi := &file_ActiveSessions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSessions.ProtoReflect.Descriptor instead.
func (*ActiveSessions) Descriptor() ([]byte, []int) {
	return file_ActiveSessions_proto_rawDescGZIP(), []int{0}
}

func (x *ActiveSessions) GetSessionsList() []*_struct.Struct {
	if x != nil {
		return x.SessionsList
	}
	return nil
}

var File_ActiveSessions_proto protoreflect.FileDescriptor

var file_ActiveSessions_proto_rawDesc = []byte{
	0x0a, 0x14, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a,
	0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x3b, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0c,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x4a, 0x5a, 0x48,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6e, 0x74, 0x61, 0x6e,
	0x67, 0x6c, 0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ActiveSessions_proto_rawDescOnce sync.Once
	file_ActiveSessions_proto_rawDescData = file_ActiveSessions_proto_rawDesc
)

func file_ActiveSessions_proto_rawDescGZIP() []byte {
	file_ActiveSessions_proto_rawDescOnce.Do(func() {
		file_ActiveSessions_proto_rawDescData = protoimpl.X.CompressGZIP(file_ActiveSessions_proto_rawDescData)
	})
	return file_ActiveSessions_proto_rawDescData
}

var file_ActiveSessions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ActiveSessions_proto_goTypes = []interface{}{
	(*ActiveSessions)(nil), // 0: reports.ActiveSessions
	(*_struct.Struct)(nil), // 1: google.protobuf.Struct
}
var file_ActiveSessions_proto_depIdxs = []int32{
	1, // 0: reports.ActiveSessions.sessionsList:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ActiveSessions_proto_init() }
func file_ActiveSessions_proto_init() {
	if File_ActiveSessions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ActiveSessions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveSessions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ActiveSessions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ActiveSessions_proto_goTypes,
		DependencyIndexes: file_ActiveSessions_proto_depIdxs,
		MessageInfos:      file_ActiveSessions_proto_msgTypes,
	}.Build()
	File_ActiveSessions_proto = out.File
	file_ActiveSessions_proto_rawDesc = nil
	file_ActiveSessions_proto_goTypes = nil
	file_ActiveSessions_proto_depIdxs = nil
}
