// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: ProtoBuffRequest.proto

package ProtoBuffRequest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoBuffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service  string `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
	Function string `protobuf:"bytes,2,opt,name=Function,proto3" json:"Function,omitempty"`
}

func (x *ProtoBuffRequest) Reset() {
	*x = ProtoBuffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ProtoBuffRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoBuffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBuffRequest) ProtoMessage() {}

func (x *ProtoBuffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ProtoBuffRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBuffRequest.ProtoReflect.Descriptor instead.
func (*ProtoBuffRequest) Descriptor() ([]byte, []int) {
	return file_ProtoBuffRequest_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoBuffRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ProtoBuffRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

var File_ProtoBuffRequest_proto protoreflect.FileDescriptor

var file_ProtoBuffRequest_proto_rawDesc = []byte{
	0x0a, 0x16, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x22, 0x48, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x3c, 0x5a, 0x3a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6e, 0x74, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75,
	0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ProtoBuffRequest_proto_rawDescOnce sync.Once
	file_ProtoBuffRequest_proto_rawDescData = file_ProtoBuffRequest_proto_rawDesc
)

func file_ProtoBuffRequest_proto_rawDescGZIP() []byte {
	file_ProtoBuffRequest_proto_rawDescOnce.Do(func() {
		file_ProtoBuffRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_ProtoBuffRequest_proto_rawDescData)
	})
	return file_ProtoBuffRequest_proto_rawDescData
}

var file_ProtoBuffRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ProtoBuffRequest_proto_goTypes = []interface{}{
	(*ProtoBuffRequest)(nil), // 0: reports.ProtoBuffRequest
}
var file_ProtoBuffRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ProtoBuffRequest_proto_init() }
func file_ProtoBuffRequest_proto_init() {
	if File_ProtoBuffRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ProtoBuffRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoBuffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ProtoBuffRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ProtoBuffRequest_proto_goTypes,
		DependencyIndexes: file_ProtoBuffRequest_proto_depIdxs,
		MessageInfos:      file_ProtoBuffRequest_proto_msgTypes,
	}.Build()
	File_ProtoBuffRequest_proto = out.File
	file_ProtoBuffRequest_proto_rawDesc = nil
	file_ProtoBuffRequest_proto_goTypes = nil
	file_ProtoBuffRequest_proto_depIdxs = nil
}
